// Physics sub-barrel — re-exports all physics-related items.
export { PhysicsTransform, RigidBody, Velocity } from "./body";
export type { PhysicsTransformData, RigidBodyData, VelocityData } from "./body";
export { CCDHeuristic } from "./ccd-heuristic";
export { CharacterController, CharacterControllerSystem } from "./character";
export type { CharacterControllerData, CharacterControllerInput } from "./character";
export { Collider, createBoxCollider, createCapsuleCollider, createConvexCollider, createMeshCollider, createSphereCollider } from "./collider";
export type { ColliderData } from "./collider";
export { CollisionEventSystem } from "./collision-system";
export { COLLISION_STARTED_CHANNEL, COLLISION_STOPPED_CHANNEL, computeCollisionEvents, computeTriggerEvents, CONTACT_CHANNEL, manifoldToStartedEvent, TRIGGER_ENTER_CHANNEL, TRIGGER_EXIT_CHANNEL } from "./events";
export type { CollisionStartedEvent, CollisionStoppedEvent, ContactEvent, TriggerEnterEvent, TriggerExitEvent } from "./events";
export { RealmTier } from "./interface";
export type { BodyDesc, BodyType, CharacterCollisionInfo, CharacterControllerDesc, CharacterControllerHandle, CharacterMoveResult, ColliderDesc, ColliderShape, ContactManifold, ImportanceWeight, IntersectionPair, IslandInfo, JointDesc, JointType, PhysicsBackend, PhysicsBody, PhysicsModuleConfig, PhysicsRealmConfig, PhysicsStats, PredictionMode, RaycastResult, RealmTierConfig, RealmTransferHook, ShapeCastResult, SnapshotHooks } from "./interface";
export { InterpolationBuffer } from "./interpolation-buffer";
export { PhysicsLifecycle } from "./lifecycle";
export type { BootstrapPhase } from "./lifecycle";
export { LoadShedder } from "./load-shedder";
export { PhysicsAccumulator } from "./physics-accumulator";
export { createPhysicsSystem } from "./physics-system";
export type { PhysicsSystemResources } from "./physics-system";
export { createRagdoll, destroyRagdoll, Ragdoll } from "./ragdoll";
export type { RagdollBoneConfig, RagdollConfig, RagdollData, RagdollJointConfig } from "./ragdoll";
export { humanoidRagdoll } from "./ragdoll-presets";
export { RagdollSystem } from "./ragdoll-system";
export { RaycastQuery } from "./raycast";
export { PhysicsRealm } from "./realm";
export { RealmManager } from "./realm-manager";
export type { RealmManagerConfig } from "./realm-manager";
export { RealmWorker, supportsNestedWorkers, supportsSharedArrayBuffer } from "./realm-worker";
export { RealmWorkerPool } from "./realm-worker-pool";
export { physicsBackendRegistry } from "./registry";
export { SafetyLayer } from "./safety";
export { SnapshotManager } from "./snapshot-manager";
export type { RealmWorkerMessage, RealmWorkerRequest, RealmWorkerResponse } from "./worker-protocol";
