// ============================================================================
// sandjongg — Mobile Entry Point (auto-generated by `draft mobile`)
// ============================================================================
//
// This is a STUB. Wire up your renderer, sim, and UI — same as src/main.tsx.
// The key difference: use createDowndraftMobileApp() instead of startGame(),
// and add touchInput config. No devtools/MCP/OSR (Electron-only).
//
// Once customized, commit this file. `draft mobile` will not regenerate it.
//

import { createDowndraftMobileApp } from "@downdraft/app/mobile";
import type { GameModule, GameSimWorker } from "@downdraft/app/renderer";

// TODO: Import your renderer, sim, UI — same as main.tsx
// import React from "react";
// import { createRoot } from "react-dom/client";
// import App from "./app";
// import { YourRenderer } from "./renderer/your-renderer";
// import "./styles/globals.css";

// TODO: Copy your GameSimWorker adapter from main.tsx (if any)
class MobileSimAdapter implements GameSimWorker {
  private sab = new SharedArrayBuffer(1024);
  async start(_config: unknown): Promise<void> { /* wire up your sim */ }
  onEvent(_cb: (msg: any) => void): void { /* wire up your sim events */ }
  getSimBuffer(): SharedArrayBuffer { return this.sab; }
  getInputBuffer(): SharedArrayBuffer { return this.sab; }
}

const mobileModule: GameModule = {
  // TODO: Wire up your renderer factory (copy from main.tsx)
  renderer: (canvas) => ({
    async init() { return true; },
    setBuffers() {},
    setupInputListeners() {},
    render() {},
    stop() {},
    getFPS() { return 0; },
  }),

  // TODO: Wire up your sim (copy from main.tsx)
  sim: () => new MobileSimAdapter(),
  simConfig: {},

  // TODO: Wire up your UI mount (copy from main.tsx)
  mountUI: (overlay) => {
    overlay.innerHTML = '<h1 style="color:white;font-family:monospace">sandjongg — mobile stub</h1>';
  },

  onReady: (_ctx) => {
    console.log("[mobile] sandjongg ready");
  },
};

createDowndraftMobileApp({
  appId: "com.downdraft.sandjongg",
  module: mobileModule,
  // TODO: Choose a touch input scheme:
  //   "dual-stick"   — 3D FPS/TPS (left=move, right=look)
  //   "tap-to-move"  — 2D/3D click-to-move
  //   "tap"          — 2D click-based (falling-sand, sandjongg)
  touchInput: { scheme: "tap" },
}).catch((e) => {
  console.error("[mobile] Fatal:", e);
});
