// ============================================================================
// Ore & lake distribution configuration — data-driven terrain generation.
//
// Ore veins are generated by Perlin worms (see terrain.ts). Each ore entry
// controls:
//   - Depth grading: a Gaussian probability curve centered at idealDepthY
//     with spread depthSpread. Multiple ores coexist at overlapping depths,
//     weighted by abundance. Hard limits minDepthY/maxDepthY prevent ores
//     from appearing outside their geological range.
//   - Vein shape: veinLength (worm steps) controls how long/stretched the
//     vein is. veinRadius (deposit radius per step) controls thickness.
//     Common ores get long thick veins; rare ores get short thin ones.
//
// Lake entries are unchanged (blob-carved cavities filled with liquid/gas).
// ============================================================================

import { Material } from "@downdraft/library-sand";

export interface OreEntry {
  material: number;
  name: string;
  // --- Depth grading (world Y coordinates, y increases downward) ---
  idealDepthY: number; // world Y where this ore is most common (Gaussian peak)
  depthSpread: number; // Gaussian standard deviation (in world Y cells)
  minDepthY: number; // hard minimum depth — no ore above this
  maxDepthY: number; // hard maximum depth — no ore below this (99999 = unlimited)
  abundance: number; // relative rarity at peak depth (0-1, higher = more common)
  // --- Vein shape (Perlin worm parameters) ---
  veinLength: number; // max worm steps (longer = more stretched vein)
  veinRadius: number; // deposit radius per step in cells (thicker vein)
}

export interface LakeEntry {
  material: number;
  name: string;
  minChunkY: number;
  maxChunkY: number;
  noiseThreshold: number;
  noiseScale: number;
  octaves: number;
  minSize: number; // minimum lake radius in cells
  maxSize: number; // maximum lake radius in cells
  fillChance: number; // 0-1, probability of a lake center spawning per candidate cell
}

// --- Ore distribution table ---
// Depth is in world Y coordinates. The surface is at ~worldY 38 (in chunk
// cy=0). Stone body starts at ~worldY 44. Each chunk is 128 cells tall.
//
//   worldY  44-500:   shallow (tin, copper, coal)
//   worldY 200-1200:  mid (iron, bauxite)
//   worldY 500-1800:  mid-deep (silver)
//   worldY 800+:      deep (gold, cobalt)
//
// Abundance controls how many worms of each type spawn at a given depth.
// At shallow depths, tin/copper/coal compete with roughly equal weight.
// At gold's ideal depth (~1200), gold and cobalt dominate. This produces
// smooth depth grading with multiple ores coexisting in transition zones.
//
// Vein shape: common ores (tin, copper, coal) get long, thick veins
// (60 steps, radius 2.0) that are easy to find and follow. Rare ores
// (gold, cobalt) get short, thin veins (30 steps, radius 1.0) that are
// harder to find and more rewarding.

export const ORE_CONFIG: OreEntry[] = [
  {
    material: Material.TinOre,
    name: "Tin",
    idealDepthY: 80,
    depthSpread: 50,
    minDepthY: 44,
    maxDepthY: 500,
    abundance: 1.0,
    veinLength: 60,
    veinRadius: 2.0,
  },
  {
    material: Material.CopperOre,
    name: "Copper",
    idealDepthY: 130,
    depthSpread: 60,
    minDepthY: 44,
    maxDepthY: 600,
    abundance: 0.9,
    veinLength: 60,
    veinRadius: 2.0,
  },
  {
    material: Material.Coal,
    name: "Coal",
    idealDepthY: 180,
    depthSpread: 80,
    minDepthY: 44,
    maxDepthY: 900,
    abundance: 1.0,
    veinLength: 70,
    veinRadius: 2.0,
  },
  {
    material: Material.IronOre,
    name: "Iron",
    idealDepthY: 350,
    depthSpread: 100,
    minDepthY: 200,
    maxDepthY: 1200,
    abundance: 0.8,
    veinLength: 50,
    veinRadius: 1.5,
  },
  {
    material: Material.BauxiteOre,
    name: "Bauxite",
    idealDepthY: 450,
    depthSpread: 100,
    minDepthY: 250,
    maxDepthY: 1300,
    abundance: 0.6,
    veinLength: 45,
    veinRadius: 1.5,
  },
  {
    material: Material.SilverOre,
    name: "Silver",
    idealDepthY: 750,
    depthSpread: 150,
    minDepthY: 500,
    maxDepthY: 1800,
    abundance: 0.5,
    veinLength: 40,
    veinRadius: 1.5,
  },
  {
    material: Material.GoldOre,
    name: "Gold",
    idealDepthY: 1200,
    depthSpread: 250,
    minDepthY: 800,
    maxDepthY: 99999,
    abundance: 0.3,
    veinLength: 30,
    veinRadius: 1.0,
  },
  {
    material: Material.CobaltOre,
    name: "Cobalt",
    idealDepthY: 1400,
    depthSpread: 250,
    minDepthY: 900,
    maxDepthY: 99999,
    abundance: 0.3,
    veinLength: 30,
    veinRadius: 1.0,
  },
];

// --- Lake / liquid distribution table ---
// Underground liquid lakes carved into stone:
//   cy 2-6:   water (shallow-mid)
//   cy 5-10:  oil (mid)
//   cy 8+:    lava (deep)
//   cy 10+:   methane gas pockets
//   cy 12+:   sulfur gas pockets

export const LAKE_CONFIG: LakeEntry[] = [
  {
    material: Material.Water,
    name: "Water",
    minChunkY: 2,
    maxChunkY: 6,
    noiseThreshold: 0.70,
    noiseScale: 0.04,
    octaves: 3,
    minSize: 8,
    maxSize: 20,
    fillChance: 0.0016,
  },
  {
    material: Material.Oil,
    name: "Oil",
    minChunkY: 5,
    maxChunkY: 10,
    noiseThreshold: 0.72,
    noiseScale: 0.04,
    octaves: 3,
    minSize: 6,
    maxSize: 16,
    fillChance: 0.006,
  },
  {
    material: Material.Lava,
    name: "Lava",
    minChunkY: 8,
    maxChunkY: 99,
    noiseThreshold: 0.74,
    noiseScale: 0.05,
    octaves: 4,
    minSize: 6,
    maxSize: 18,
    fillChance: 0.007,
  },
  {
    material: Material.MethaneGas,
    name: "Methane",
    minChunkY: 10,
    maxChunkY: 99,
    noiseThreshold: 0.76,
    noiseScale: 0.06,
    octaves: 3,
    minSize: 5,
    maxSize: 14,
    fillChance: 0.005,
  },
  {
    material: Material.SulfurGas,
    name: "Sulfur",
    minChunkY: 12,
    maxChunkY: 99,
    noiseThreshold: 0.78,
    noiseScale: 0.06,
    octaves: 3,
    minSize: 5,
    maxSize: 12,
    fillChance: 0.004,
  },
];

// --- Cavity (cave) configuration ---

export const CAVITY_CONFIG = {
  noiseScale: 0.03,
  noiseThreshold: 0.72,
  octaves: 4,
  minChunkY: 1, // no caves at surface
  maxChunkY: 99,
};

// --- Surface configuration ---

export const SURFACE_CONFIG = {
  surfaceYRatio: 0.3, // surface at 30% down in chunk cy=0
  grassDepth: 1, // grass layer thickness
  dirtDepth: 5, // base dirt layer thickness below grass
  dirtDepthVariation: 4, // max ± variation in dirt thickness per column
  dirtDepthNoiseScale: 0.03, // spatial frequency of dirt depth variation
  noiseScale: 0.02, // surface height variation
  noiseAmplitude: 8, // max height variation in cells
};

// --- Perlin worm system parameters ---
// These control the global vein generation behavior. Per-ore tuning is in
// OreEntry (veinLength, veinRadius). These are the shared structural params.

export const WORM_CONFIG = {
  // Seed grid spacing: one potential worm spawn point every N world cells.
  // Smaller = more worms = denser ore. 32 → ~16 seed cells per 128-cell chunk.
  seedGrid: 32,
  // Probability that a seed cell actually spawns a worm.
  spawnChance: 0.12,
  // Distance the worm travels per step (in cells). Smaller = smoother path
  // with more overlap between deposits (continuous vein).
  stepSize: 1.5,
  // Maximum direction change per step (radians). Higher = more curvy veins.
  turnRate: 0.35,
  // Spatial frequency of the noise that perturbs the worm's direction.
  // Lower = longer-wavelength curves, higher = tighter wiggles.
  noiseScale: 0.04,
  // Early exit: if a worm has been outside the chunk neighborhood for this
  // many consecutive steps, stop simulating it (optimization).
  maxStepsOutside: 15,
};
