// ============================================================================
// Terrain generation — procedural depth-stratified world.
//
// Each chunk is generated deterministically from (cx, cy, seed):
//   - Surface band (cy=0): grass + dirt with noise-based height variation
//   - Stone body: solid stone with noise-based cavities (caves)
//   - Ore veins: depth-gated noise blobs within stone (tin, copper, iron, etc.)
//   - Underground lakes: carved cavities filled with water/oil/lava by depth
//   - Gas pockets: carved cavities filled with methane/sulfur gas (deep)
//
// All cells start frozen (wakeTick = 0). The simulation unfreezes cells when
// they are dug or disturbed.
// ============================================================================

import { Material, packCell } from "@downdraft/library-sand";
import { CHUNK_H, CHUNK_W } from "../shared/constants";
import type { Chunk } from "../shared/types";
import { isStaticUntilDamaged } from "./material-overrides";
import { cellHash, mulberry32, worldFbm, worldValueNoise } from "./noise";
import {
    CAVITY_CONFIG,
    LAKE_CONFIG,
    ORE_CONFIG,
    SURFACE_CONFIG,
    WORM_CONFIG,
    type LakeEntry,
    type OreEntry
} from "./ore-config";

function chunkKey(cx: number, cy: number): string {
  return `${cx},${cy}`;
}

/**
 * Compute the surface height (in world Y coords) at a given world X.
 * Uses fBm noise for gentle rolling hills.
 */
function surfaceHeightAt(wx: number, seed: number): number {
  const baseSurface = Math.floor(CHUNK_H * SURFACE_CONFIG.surfaceYRatio);
  const noise = worldFbm(
    wx,
    0,
    seed,
    SURFACE_CONFIG.noiseScale,
    3,
  );
  // noise is ~0-1, center it around 0 and scale by amplitude
  const variation = Math.floor((noise - 0.5) * 2 * SURFACE_CONFIG.noiseAmplitude);
  return baseSurface + variation;
}

/**
 * Compute the dirt layer thickness at a given world X.
 * Uses an independent noise field (different Y offset) so dirt depth varies
 * per column independently of the surface height, giving a more natural
 * uneven dirt layer rather than a constant-thickness band.
 */
function dirtDepthAt(wx: number, seed: number): number {
  const base = SURFACE_CONFIG.dirtDepth;
  const variation = SURFACE_CONFIG.dirtDepthVariation;
  const noise = worldFbm(
    wx,
    1000, // offset Y so this noise field is independent from surfaceHeightAt
    seed,
    SURFACE_CONFIG.dirtDepthNoiseScale,
    2,
  );
  // noise ~0-1 → variation centered at 0, range [-variation, +variation]
  const delta = Math.floor((noise - 0.5) * 2 * variation);
  return Math.max(1, base + delta); // at least 1 cell of dirt
}

// ============================================================================
// Perlin worm ore vein generation
//
// Instead of thresholded noise (which produces blob-shaped deposits), ore
// veins are generated by "worms" that walk through the stone body depositing
// ore along their path. This produces long, winding, connected veins that
// look like mineralized fractures — the same technique used by Minecraft.
//
// How it works:
//   1. The world is divided into a coarse seed grid (every WORM_CONFIG.seedGrid
//      cells). At each seed point, a worm may spawn (deterministic hash check).
//   2. The worm's ore type is chosen by depth-weighted Gaussian selection at
//      its spawn point — multiple ore types coexist, grading smoothly with depth.
//   3. The worm walks in a noise-perturbed direction for up to ore.veinLength
//      steps, depositing ore in a small radius at each step.
//   4. When generating a chunk, worms from seed cells in a neighborhood are
//      simulated so veins span chunk boundaries seamlessly.
//
// Determinism: each worm is seeded by its grid cell coordinates + world seed.
// The entire path is deterministic, so a vein is identical regardless of
// which chunk is being generated. This guarantees seamless chunk-spanning.
// ============================================================================

/**
 * Pick an ore type for a worm spawning at (worldX, worldY) using depth-weighted
 * Gaussian probability. Multiple ores can coexist at overlapping depths; the
 * abundance parameter controls the relative mix. Returns null if no ore is
 * valid at this depth.
 */
function pickOreByDepth(worldX: number, worldY: number, seed: number): OreEntry | null {
  let totalWeight = 0;
  const weights: number[] = [];
  for (const ore of ORE_CONFIG) {
    if (worldY < ore.minDepthY || worldY > ore.maxDepthY) {
      weights.push(0);
      continue;
    }
    const depthDelta = worldY - ore.idealDepthY;
    const w = ore.abundance * Math.exp(-(depthDelta * depthDelta) / (2 * ore.depthSpread * ore.depthSpread));
    weights.push(w);
    totalWeight += w;
  }
  if (totalWeight === 0) return null;

  // Deterministic pick using the seed cell's hash
  const sgx = Math.floor(worldX / WORM_CONFIG.seedGrid);
  const sgy = Math.floor(worldY / WORM_CONFIG.seedGrid);
  const r = cellHash(sgx, sgy, 0, 0, seed + 4242) * totalWeight;
  let cumulative = 0;
  for (let i = 0; i < ORE_CONFIG.length; i++) {
    cumulative += weights[i];
    if (r < cumulative) return ORE_CONFIG[i];
  }
  return ORE_CONFIG[ORE_CONFIG.length - 1];
}

/**
 * Deposit ore material in a small radius around a world coordinate, but only
 * into the chunk being generated (chunkCx, chunkCy). Only overwrites stone —
 * cavities, dirt, existing ores, and walls are preserved.
 *
 * For tin and copper ore, the per-cell gravity field is set to 0 so they stay
 * embedded in the ground until mined (dig() re-enables gravity).
 */
function depositOreAt(
  wx: number,
  wy: number,
  radius: number,
  material: number,
  grid: Uint32Array,
  fields: Uint8Array,
  chunkCx: number,
  chunkCy: number,
  shade: () => number,
): void {
  const chunkWorldX = chunkCx * CHUNK_W;
  const chunkWorldY = chunkCy * CHUNK_H;
  const lx = Math.floor(wx - chunkWorldX);
  const ly = Math.floor(wy - chunkWorldY);
  const r = Math.ceil(radius);
  const r2 = radius * radius;

  for (let dy = -r; dy <= r; dy++) {
    for (let dx = -r; dx <= r; dx++) {
      if (dx * dx + dy * dy > r2) continue;
      const x = lx + dx;
      const y = ly + dy;
      if (x < 0 || x >= CHUNK_W || y < 0 || y >= CHUNK_H) continue;
      const idx = y * CHUNK_W + x;
      const existing = grid[idx] & 0xff;
      // Only overwrite stone (preserve cavities, dirt, existing ores, walls)
      if (existing !== Material.Stone) continue;
      grid[idx] = packCell(material, 0, shade());
      // Ores and coal are static until mined: set per-cell gravity=0 so they
      // don't fall while embedded in stone. The mining system restores the
      // gravity field when the cell is dislodged (cellDamage >= hardness).
      if (isStaticUntilDamaged(material)) {
        fields[idx * 4 + 0] = 0; // gravity field = 0 (no falling)
      }
    }
  }
}

/**
 * Simulate a single Perlin worm from its spawn point. The worm walks in a
 * noise-perturbed direction, depositing ore at each step. Only deposits that
 * fall within the target chunk (chunkCx, chunkCy) are written to the grid.
 *
 * Early-exit: if the worm wanders outside the chunk neighborhood for too many
 * consecutive steps, it stops (optimization — the worm is unlikely to return).
 */
function simulateWorm(
  spawnX: number,
  spawnY: number,
  ore: OreEntry,
  seed: number,
  grid: Uint32Array,
  fields: Uint8Array,
  chunkCx: number,
  chunkCy: number,
  shade: () => number,
): void {
  // Initial direction: deterministic from spawn position + ore type
  const dirHash = cellHash(
    Math.floor(spawnX / WORM_CONFIG.seedGrid),
    Math.floor(spawnY / WORM_CONFIG.seedGrid),
    0,
    0,
    seed + ore.material * 13,
  );
  let angle = dirHash * Math.PI * 2;

  const maxSteps = ore.veinLength;
  const radius = ore.veinRadius;
  const stepSize = WORM_CONFIG.stepSize;
  const turnRate = WORM_CONFIG.turnRate;
  const noiseScale = WORM_CONFIG.noiseScale;

  let x = spawnX;
  let y = spawnY;

  // Chunk bounds + margin for early-exit check
  const chunkWorldX = chunkCx * CHUNK_W;
  const chunkWorldY = chunkCy * CHUNK_H;
  const margin = radius + stepSize * WORM_CONFIG.maxStepsOutside;
  const minX = chunkWorldX - margin;
  const maxX = chunkWorldX + CHUNK_W + margin;
  const minY = chunkWorldY - margin;
  const maxY = chunkWorldY + CHUNK_H + margin;

  let stepsOutside = 0;

  for (let step = 0; step < maxSteps; step++) {
    // Deposit ore at current position
    depositOreAt(x, y, radius, ore.material, grid, fields, chunkCx, chunkCy, shade);

    // Perturb direction using noise (veins curve and meander)
    const turnNoise = worldFbm(x, y, seed + ore.material * 101, noiseScale, 2);
    angle += (turnNoise - 0.5) * 2 * turnRate;

    // Move forward
    x += Math.cos(angle) * stepSize;
    y += Math.sin(angle) * stepSize;

    // Early exit if the worm has wandered far outside the chunk
    if (x < minX || x > maxX || y < minY || y > maxY) {
      stepsOutside++;
      if (stepsOutside > WORM_CONFIG.maxStepsOutside) break;
    } else {
      stepsOutside = 0;
    }
  }
}

/**
 * Generate all ore veins that intersect a chunk by simulating worms from seed
 * cells in a neighborhood. The neighborhood radius is determined by the
 * maximum worm travel distance, ensuring veins span chunk boundaries.
 *
 * Called as Step 3 of generateChunk, after base terrain + cavities, before
 * lakes. Only overwrites stone — cavities and dirt are preserved.
 */
function generateOreWorms(
  cx: number,
  cy: number,
  seed: number,
  grid: Uint32Array,
  fields: Uint8Array,
  shade: () => number,
): void {
  const chunkWorldX = cx * CHUNK_W;
  const chunkWorldY = cy * CHUNK_H;

  // Find the maximum vein length across all ores to determine neighborhood
  const maxVeinLen = ORE_CONFIG.reduce((m, o) => Math.max(m, o.veinLength), 0);
  const maxTravel = maxVeinLen * WORM_CONFIG.stepSize;
  const neighborhoodRadius = Math.ceil(maxTravel / WORM_CONFIG.seedGrid) + 1;

  // Find the seed grid origin closest to the chunk's top-left corner
  const sgOriginX = Math.floor(chunkWorldX / WORM_CONFIG.seedGrid);
  const sgOriginY = Math.floor(chunkWorldY / WORM_CONFIG.seedGrid);

  // Iterate seed cells in the neighborhood and simulate any worms that spawn
  for (let sgy = sgOriginY - neighborhoodRadius; sgy <= sgOriginY + neighborhoodRadius; sgy++) {
    for (let sgx = sgOriginX - neighborhoodRadius; sgx <= sgOriginX + neighborhoodRadius; sgx++) {
      // Deterministic spawn check
      const spawnHash = cellHash(sgx, sgy, 0, 0, seed + 7777);
      if (spawnHash >= WORM_CONFIG.spawnChance) continue;

      // Worm spawn position (center of the seed cell)
      const spawnX = sgx * WORM_CONFIG.seedGrid + WORM_CONFIG.seedGrid * 0.5;
      const spawnY = sgy * WORM_CONFIG.seedGrid + WORM_CONFIG.seedGrid * 0.5;

      // Pick ore type by depth at spawn point
      const ore = pickOreByDepth(spawnX, spawnY, seed);
      if (!ore) continue;

      simulateWorm(spawnX, spawnY, ore, seed, grid, fields, cx, cy, shade);
    }
  }
}

/**
 * Check if a world cell is inside a cavity (cave).
 * Cavities are empty pockets in the stone body, shaped by noise.
 */
function isCavity(wx: number, wy: number, cy: number, seed: number): boolean {
  if (cy < CAVITY_CONFIG.minChunkY || cy > CAVITY_CONFIG.maxChunkY) return false;
  const noise = worldFbm(wx, wy, seed, CAVITY_CONFIG.noiseScale, CAVITY_CONFIG.octaves);
  return noise > CAVITY_CONFIG.noiseThreshold;
}

/**
 * Check if a world cell is the center of a lake/gas pocket.
 * Lake centers are sparse — determined by a low-probability hash check.
 * If this cell is a lake center, the lake is carved as a blob around it.
 */
function lakeCenterAt(
  wx: number,
  wy: number,
  cy: number,
  seed: number,
): LakeEntry | null {
  for (const lake of LAKE_CONFIG) {
    if (cy < lake.minChunkY || cy > lake.maxChunkY) continue;

    // Check noise threshold for lake region
    const noise = worldFbm(wx, wy, seed, lake.noiseScale, lake.octaves);
    if (noise < lake.noiseThreshold) continue;

    // Sparse center check
    const hash = cellHash(
      Math.floor(wx / CHUNK_W),
      Math.floor(wy / CHUNK_H),
      wx % CHUNK_W,
      wy % CHUNK_H,
      seed + lake.material + 7777,
    );
    if (hash < lake.fillChance) {
      return lake;
    }
  }
  return null;
}

/**
 * Carve a circular lake/pocket around a center point (in WORLD coords).
 * Fills cells within the radius with the lake material (overwriting stone).
 * Does not overwrite existing non-stone cells (preserves ores/cavities at edges).
 *
 * The center can be in a neighboring chunk — only the cells that fall within
 * the chunk being generated (chunkCx, chunkCy) are written. This lets lakes
 * span chunk boundaries seamlessly: each chunk carves the portion of the lake
 * that falls within its own cells, using the same deterministic center.
 *
 * Depth gating: cells outside the lake's [minChunkY, maxChunkY] range are
 * skipped. This prevents a lake center near a depth boundary (e.g. lava at
 * the top of chunk 8) from carving into chunks above its depth range (e.g.
 * chunk 7). Horizontal spanning is preserved — only the vertical depth gate
 * is enforced.
 */
function carveLake(
  grid: Uint32Array,
  chunkCx: number,
  chunkCy: number,
  centerWX: number,
  centerWY: number,
  radius: number,
  material: number,
  minChunkY: number,
  maxChunkY: number,
  seed: number,
  shade: () => number,
): void {
  const r2 = radius * radius;
  const chunkWorldX = chunkCx * CHUNK_W;
  const chunkWorldY = chunkCy * CHUNK_H;
  // Center in chunk-local coords (may be negative or >= CHUNK_W/H if the
  // center is in a neighboring chunk — that's fine, the bounds clamp below
  // ensures we only write to cells within this chunk).
  const lcx = centerWX - chunkWorldX;
  const lcy = centerWY - chunkWorldY;
  const x0 = Math.max(0, lcx - radius);
  const x1 = Math.min(CHUNK_W - 1, lcx + radius);
  const y0 = Math.max(0, lcy - radius);
  const y1 = Math.min(CHUNK_H - 1, lcy + radius);

  for (let y = y0; y <= y1; y++) {
    const cellWY = chunkWorldY + y;
    // Depth gate: skip cells outside the lake's valid chunk-Y range. This
    // prevents lakes from spilling across depth boundaries (e.g. lava from
    // chunk 8 carving up into chunk 7) while still allowing horizontal
    // chunk-border spanning.
    const cellCY = Math.floor(cellWY / CHUNK_H);
    if (cellCY < minChunkY || cellCY > maxChunkY) continue;
    for (let x = x0; x <= x1; x++) {
      const dx = x - lcx;
      const dy = y - lcy;
      // Use noise to make the lake blob irregular (world coords → deterministic
      // across chunk boundaries, so the lake shape is consistent regardless of
      // which chunk is carving it)
      const distNoise = worldValueNoise(
        chunkWorldX + x,
        cellWY,
        seed + material * 31,
        0.15,
      );
      const effectiveR2 = r2 * (0.7 + distNoise * 0.6);
      if (dx * dx + dy * dy <= effectiveR2) {
        const idx = y * CHUNK_W + x;
        const existing = grid[idx] & 0xff;
        // Only carve into stone (don't overwrite ores or existing liquids)
        if (existing === Material.Stone || existing === Material.Dirt) {
          grid[idx] = packCell(material, 0, shade());
        }
      }
    }
  }
}

/**
 * Generate a chunk's grid + fields.
 *
 * Generation order:
 *   1. Fill with stone (underground) or sky+grass+dirt (surface)
 *   2. Carve cavities (caves) — set to empty
 *   3. Place ore veins (overwrite stone with ore material)
 *   4. Carve lakes/gas pockets (overwrite stone with liquid/gas)
 *
 * All cells start frozen (wakeTick = 0).
 */
export function generateChunk(cx: number, cy: number, seed: number): Chunk {
  const cells = CHUNK_W * CHUNK_H;
  const grid = new Uint32Array(cells);
  const fields = new Uint8Array(cells * 4);
  const bgGrid = new Uint32Array(cells); // background layer — empty (no build materials)
  const wakeTick = new Uint32Array(cells); // all frozen

  // Initialize fields to defaults (gravity=128, temp=128)
  for (let i = 0; i < cells * 4; i += 4) {
    fields[i + 0] = 128; // gravity
    fields[i + 1] = 128; // temp
  }

  // Use a per-chunk PRNG for shade randomization (deterministic)
  const rng = mulberry32(cx * 73856093 + cy * 19349663 + seed);
  const shade = () => Math.floor(rng() * 4);

  // --- Step 1: Base terrain (sky / grass / dirt / stone) ---
  if (cy < 0) {
    // Above-surface chunks: empty sky
    // grid is already zero-filled
  } else if (cy === 0) {
    // Surface chunk: sky → grass → dirt → stone
    for (let x = 0; x < CHUNK_W; x++) {
      const wx = cx * CHUNK_W + x;
      const surfaceY = surfaceHeightAt(wx, seed);
      const dirtDepth = dirtDepthAt(wx, seed);
      for (let y = 0; y < CHUNK_H; y++) {
        const idx = y * CHUNK_W + x;
        if (y < surfaceY) {
          // Sky (empty)
          grid[idx] = 0;
        } else if (y < surfaceY + SURFACE_CONFIG.grassDepth) {
          // Grass layer
          grid[idx] = packCell(Material.Grass, 0, shade());
        } else if (y < surfaceY + SURFACE_CONFIG.grassDepth + dirtDepth) {
          // Dirt layer (thickness varies per column for natural look)
          grid[idx] = packCell(Material.Dirt, 0, shade());
        } else {
          // Stone
          grid[idx] = packCell(Material.Stone, 0, shade());
        }
      }
    }
  } else {
    // Underground chunks: solid stone
    for (let i = 0; i < cells; i++) {
      grid[i] = packCell(Material.Stone, 0, shade());
    }
  }

  // --- Step 2: Carve cavities (caves) ---
  if (cy >= CAVITY_CONFIG.minChunkY) {
    for (let y = 0; y < CHUNK_H; y++) {
      for (let x = 0; x < CHUNK_W; x++) {
        const wx = cx * CHUNK_W + x;
        const wy = cy * CHUNK_H + y;
        const idx = y * CHUNK_W + x;
        // Don't carve cavities in the sky or grass/dirt layers
        const mat = grid[idx] & 0xff;
        if (mat !== Material.Stone) continue;
        if (isCavity(wx, wy, cy, seed)) {
          grid[idx] = 0; // empty cave
        }
      }
    }
  }

  // --- Step 3: Place ore veins (Perlin worms → stretched, winding veins) ---
  // Worms are simulated from seed cells in a neighborhood of this chunk so
  // veins span chunk boundaries. Only overwrites stone — cavities and dirt
  // are preserved. Tin/copper get gravity=0 so they stay embedded until mined.
  if (cy >= 0) {
    generateOreWorms(cx, cy, seed, grid, fields, shade);
  }

  // --- Step 4: Carve lakes / gas pockets ---
  // Lake centers are detected per-cell via a deterministic hash. A lake center
  // near a chunk border must carve into neighboring chunks too — so we iterate
  // candidate centers in a neighborhood extending by the max lake radius beyond
  // the chunk borders. Each center carves only the cells that fall within THIS
  // chunk (carveLake skips out-of-bounds cells). This guarantees lakes span
  // chunk boundaries seamlessly, matching the ore-worm neighborhood approach.
  if (cy >= 0) {
    const maxLakeRadius = LAKE_CONFIG.reduce((m, l) => Math.max(m, l.maxSize), 0);
    const chunkWorldX = cx * CHUNK_W;
    const chunkWorldY = cy * CHUNK_H;
    const startWX = chunkWorldX - maxLakeRadius;
    const endWX = chunkWorldX + CHUNK_W + maxLakeRadius;
    const startWY = chunkWorldY - maxLakeRadius;
    const endWY = chunkWorldY + CHUNK_H + maxLakeRadius;
    for (let wy = startWY; wy < endWY; wy++) {
      for (let wx = startWX; wx < endWX; wx++) {
        // Use the center cell's own chunk Y for the depth-range check
        // (a center in a neighboring chunk is gated by its own depth, not
        // the chunk being generated).
        const centerCy = Math.floor(wy / CHUNK_H);
        const lake = lakeCenterAt(wx, wy, centerCy, seed);
        if (!lake) continue;
        // Determine lake radius (deterministic from the center's chunk + local
        // coords — same radius regardless of which chunk is carving it)
        const centerCx = Math.floor(wx / CHUNK_W);
        const centerLx = wx - centerCx * CHUNK_W;
        const centerLy = wy - centerCy * CHUNK_H;
        const sizeHash = cellHash(centerCx, centerCy, centerLx, centerLy, seed + lake.material + 9999);
        const radius = lake.minSize + sizeHash * (lake.maxSize - lake.minSize);
        carveLake(grid, cx, cy, wx, wy, Math.floor(radius), lake.material, lake.minChunkY, lake.maxChunkY, seed, shade);
      }
    }
  }

  return {
    cx,
    cy,
    grid,
    fields,
    bgGrid,
    wakeTick,
    generated: true,
    dirty: false,
    active: false,
  };
}

export { chunkKey };

// --- Exported helpers for testing ---

    export { dirtDepthAt, generateOreWorms, isCavity, lakeCenterAt, pickOreByDepth, surfaceHeightAt };
    export type { LakeEntry, OreEntry };

