// Generates minimal valid test fixture files for formats we couldn't download.
// Run: bun tests/fixtures/generate-fixtures.ts

import { mkdirSync, writeFileSync } from "fs";
import { join } from "path";

const FIXTURES = join(import.meta.dir);

// ─── PLY (ASCII) ───────────────────────────────────────────────────────────
// Simple tetrahedron with normals
function generatePLY(): string {
  const lines: string[] = [
    "ply",
    "format ascii 1.0",
    "comment Generated by generate-fixtures.ts",
    "element vertex 4",
    "property float x",
    "property float y",
    "property float z",
    "property float nx",
    "property float ny",
    "property float nz",
    "element face 4",
    "property list uchar int vertex_indices",
    "end_header",
    // vertices: 4 corners of a tetrahedron
    "0 0 0  0 0 1",
    "1 0 0  1 0 0",
    "0 1 0  0 1 0",
    "0 0 1  0 0 1",
    // faces
    "3 0 1 2",
    "3 0 2 3",
    "3 0 3 1",
    "3 1 3 2",
  ];
  return lines.join("\n") + "\n";
}

// ─── PLY (binary little-endian) ────────────────────────────────────────────
function generateBinaryPLY(): ArrayBuffer {
  const header = [
    "ply",
    "format binary_little_endian 1.0",
    "comment Generated by generate-fixtures.ts",
    "element vertex 4",
    "property float x",
    "property float y",
    "property float z",
    "element face 4",
    "property list uchar uint vertex_indices",
    "end_header",
    "",
  ].join("\n");

  const headerBytes = new TextEncoder().encode(header);
  // 4 vertices * 3 floats * 4 bytes = 48 bytes
  // 4 faces * (1 byte count + 3 * 4 bytes indices) = 52 bytes
  const dataBytes = 48 + 52;
  const buf = new ArrayBuffer(headerBytes.length + dataBytes);
  const view = new DataView(buf);
  const u8 = new Uint8Array(buf);

  u8.set(headerBytes, 0);
  let offset = headerBytes.length;

  // Vertices
  const verts = [
    [0, 0, 0],
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1],
  ];
  verts.forEach((v) => {
    v.forEach((c) => {
      view.setFloat32(offset, c, true);
      offset += 4;
    });
  });

  // Faces
  const faces = [
    [0, 1, 2],
    [0, 2, 3],
    [0, 3, 1],
    [1, 3, 2],
  ];
  faces.forEach((f) => {
    view.setUint8(offset, 3);
    offset += 1;
    f.forEach((idx) => {
      view.setUint32(offset, idx, true);
      offset += 4;
    });
  });

  return buf;
}

// ─── 3DS (minimal binary) ──────────────────────────────────────────────────
function generate3DS(): ArrayBuffer {
  // Minimal 3DS with one object containing a single triangle mesh
  const chunks: { id: number; data: Uint8Array }[] = [];

  // Helper to build a chunk
  function buildChunk(id: number, data: Uint8Array): Uint8Array {
    const buf = new ArrayBuffer(6 + data.length);
    const view = new DataView(buf);
    view.setUint16(0, id, true);
    view.setUint32(2, 6 + data.length, true);
    new Uint8Array(buf, 6).set(data);
    return new Uint8Array(buf);
  }

  // Object name string (null-terminated)
  const objName = new TextEncoder().encode("TestCube\0");

  // Vertices chunk (0x4110): 3 vertices for a triangle
  const vertData = new ArrayBuffer(2 + 3 * 12);
  const vView = new DataView(vertData);
  vView.setUint16(0, 3, true); // count
  const verts = [
    [0, 0, 0],
    [1, 0, 0],
    [0, 1, 0],
  ];
  let vo = 2;
  verts.forEach((v) => {
    vView.setFloat32(vo, v[0], true); vo += 4;
    vView.setFloat32(vo, v[1], true); vo += 4;
    vView.setFloat32(vo, v[2], true); vo += 4;
  });
  const vertChunk = buildChunk(0x4110, new Uint8Array(vertData));

  // Faces chunk (0x4120): 1 face
  const faceData = new ArrayBuffer(2 + 1 * 8);
  const fView = new DataView(faceData);
  fView.setUint16(0, 1, true); // count
  fView.setUint16(2, 0, true); // v0
  fView.setUint16(4, 1, true); // v1
  fView.setUint16(6, 2, true); // v2
  // face flags would be at offset 8 but we only have 1 face so skip
  const faceChunk = buildChunk(0x4120, new Uint8Array(faceData));

  // Trimesh chunk (0x4100) contains vert + face chunks
  const trimeshContent = new Uint8Array(vertChunk.length + faceChunk.length);
  trimeshContent.set(vertChunk, 0);
  trimeshContent.set(faceChunk, vertChunk.length);
  const trimeshChunk = buildChunk(0x4100, trimeshContent);

  // Object chunk (0x4000) contains name + trimesh
  const objContent = new Uint8Array(objName.length + trimeshChunk.length);
  objContent.set(objName, 0);
  objContent.set(trimeshChunk, objName.length);
  const objChunk = buildChunk(0x4000, objContent);

  // Edit chunk (0x3d3d) contains object
  const editChunk = buildChunk(0x3d3d, objChunk);

  // Main chunk (0x4d4d) contains edit
  const mainChunk = buildChunk(0x4d4d, editChunk);

  return mainChunk.buffer as ArrayBuffer;
}

// ─── DDS (uncompressed RGBA8, 4x4) ─────────────────────────────────────────
function generateDDS(): ArrayBuffer {
  // DDS header is 128 bytes
  const buf = new ArrayBuffer(128 + 4 * 4 * 4); // header + 4x4 RGBA8 pixels
  const view = new DataView(buf);
  const u8 = new Uint8Array(buf);

  // Magic "DDS "
  u8[0] = 0x44; u8[1] = 0x44; u8[2] = 0x53; u8[3] = 0x20;

  // DDS_HEADER
  view.setUint32(4, 124, true);       // dwSize
  view.setUint32(8, 0x1007, true);    // dwFlags: DDSD_CAPS | DDSD_HEIGHT | DDSD_WIDTH | DDSD_PIXELFORMAT
  view.setUint32(12, 4, true);        // dwHeight
  view.setUint32(16, 4, true);        // dwWidth
  view.setUint32(20, 4 * 4 * 4, true); // dwPitchOrLinearSize
  view.setUint32(24, 0, true);        // dwDepth
  view.setUint32(28, 0, true);        // dwMipMapCount
  // dwReserved1[11] = 0 (already zeroed)

  // DDS_PIXELFORMAT at offset 76
  view.setUint32(76, 32, true);       // dwSize
  view.setUint32(80, 0x41, true);     // dwFlags: DDPF_RGB | DDPF_ALPHAPIXELS
  view.setUint32(84, 0x20, true);     // dwFourCC (unused for uncompressed)
  view.setUint32(88, 32, true);       // dwRGBBitCount
  view.setUint32(92, 0x00FF0000, true); // dwRBitMask
  view.setUint32(96, 0x0000FF00, true); // dwGBitMask
  view.setUint32(100, 0x000000FF, true); // dwBBitMask
  view.setUint32(104, 0xFF000000, true); // dwABitMask

  // dwCaps at offset 108
  view.setUint32(108, 0x1000, true);  // DDSCAPS_TEXTURE

  // Pixel data: 4x4 RGBA pixels (red gradient)
  let offset = 128;
  for (let y = 0; y < 4; y++) {
    for (let x = 0; x < 4; x++) {
      view.setUint8(offset, x * 64);     // R
      view.setUint8(offset + 1, y * 64); // G
      view.setUint8(offset + 2, 128);    // B
      view.setUint8(offset + 3, 255);    // A
      offset += 4;
    }
  }

  return buf;
}

// ─── KTX2 (uncompressed RGBA8, 4x4) ────────────────────────────────────────
function generateKTX2(): ArrayBuffer {
  // KTX2 header is 80 bytes + format description (28 bytes) + level index
  const width = 4, height = 4;
  const pixelSize = width * height * 4; // RGBA8
  const headerSize = 80;
  const formatSize = 28;
  const levelCount = 1;
  const levelIndexSize = levelCount * 12; // each entry: 3 x uint64
  const dataOffset = headerSize + formatSize + levelIndexSize;

  const buf = new ArrayBuffer(dataOffset + pixelSize);
  const view = new DataView(buf);
  const u8 = new Uint8Array(buf);

  // KTX2 magic: 0xAB 4B 54 58 20 32 30 BB 0D 0A 1A 0A
  const magic = [0xAB, 0x4B, 0x54, 0x58, 0x20, 0x32, 0x30, 0xBB, 0x0D, 0x0A, 0x1A, 0x0A];
  for (let i = 0; i < magic.length; i++) u8[i] = magic[i];

  // KTX2 header fields (all uint32 per spec, loader reads them as uint32)
  view.setUint32(12, 37, true);           // vkFormat = VK_FORMAT_R8G8B8A8_UNORM
  view.setUint32(16, 1, true);            // typeSize
  view.setUint32(20, width, true);        // pixelWidth
  view.setUint32(24, height, true);       // pixelHeight
  view.setUint32(28, 0, true);            // pixelDepth
  view.setUint32(32, 0, true);            // layerCount
  view.setUint32(36, 1, true);            // faceCount
  view.setUint32(40, levelCount, true);   // levelCount
  // Remaining header fields (44-79) are supercompressionScheme, dfdByteOffset,
  // dfdByteLength, kvdByteOffset, kvdByteLength, supercompressionGlobalBlock
  // Set them all to 0 (already zeroed by ArrayBuffer)

  // Pixel data
  let offset = dataOffset;
  for (let y = 0; y < height; y++) {
    for (let x = 0; x < width; x++) {
      view.setUint8(offset, x * 64);     // R
      view.setUint8(offset + 1, y * 64); // G
      view.setUint8(offset + 2, 128);    // B
      view.setUint8(offset + 3, 255);    // A
      offset += 4;
    }
  }

  return buf;
}

// ─── Write all files ────────────────────────────────────────────────────────
mkdirSync(join(FIXTURES, "models"), { recursive: true });
mkdirSync(join(FIXTURES, "textures"), { recursive: true });

// PLY ASCII
writeFileSync(join(FIXTURES, "models", "tetra.ply"), generatePLY());
console.log("✓ models/tetra.ply (ASCII PLY)");

// PLY Binary
const plyBin = generateBinaryPLY();
writeFileSync(join(FIXTURES, "models", "tetra_binary.ply"), Buffer.from(plyBin));
console.log("✓ models/tetra_binary.ply (Binary PLY)");

// 3DS
const ds3 = generate3DS();
writeFileSync(join(FIXTURES, "models", "triangle.3ds"), Buffer.from(ds3));
console.log("✓ models/triangle.3ds");

// DDS
const dds = generateDDS();
writeFileSync(join(FIXTURES, "textures", "test_rgba8.dds"), Buffer.from(dds));
console.log("✓ textures/test_rgba8.dds");

// KTX2
const ktx2 = generateKTX2();
writeFileSync(join(FIXTURES, "textures", "test_rgba8.ktx2"), Buffer.from(ktx2));
console.log("✓ textures/test_rgba8.ktx2");

console.log("\nAll fixture files generated successfully.");
