// ============================================================================
// op-ids — numeric op id constants. Auto-generated by shim-gen in a real
// build, but hand-maintained here for the initial subset. Adding an op =
// append a new id here AND an entry in op-table.ts.
// ============================================================================

// Reserved / control
export const OP_RELEASE = 0; // worker → main: release a handle (GC)
export const OP_TRACK_LAYOUT = 1; // worker → main: subscribe handle to LayoutChannel
export const OP_UNTRACK_LAYOUT = 2; // worker → main: unsubscribe

// Document
export const OP_DOCUMENT_CREATE_ELEMENT = 10;
export const OP_DOCUMENT_CREATE_TEXT_NODE = 11;
export const OP_DOCUMENT_CREATE_DOCUMENT_FRAGMENT = 12;
export const OP_DOCUMENT_GET_ELEMENT_BY_ID = 13;
export const OP_DOCUMENT_QUERY_SELECTOR = 14;
export const OP_DOCUMENT_QUERY_SELECTOR_ALL = 15;
export const OP_DOCUMENT_GET_DOCUMENT_ELEMENT = 16; // → <html>
export const OP_DOCUMENT_GET_HEAD = 17;
export const OP_DOCUMENT_GET_BODY = 18;
export const OP_DOCUMENT_CREATE_COMMENT = 19;
export const OP_DOCUMENT_CREATE_ELEMENT_NS = 20;
export const OP_DOCUMENT_CREATE_EVENT = 21;
export const OP_DOCUMENT_GET_READY_STATE = 22;
export const OP_DOCUMENT_GET_VISIBILITY_STATE = 23;
export const OP_DOCUMENT_GET_DEFAULT_VIEW = 24;
export const OP_DOCUMENT_EXIT_POINTER_LOCK = 25;

// Node
export const OP_NODE_APPEND_CHILD = 30;
export const OP_NODE_REMOVE_CHILD = 31;
export const OP_NODE_INSERT_BEFORE = 32;
export const OP_NODE_REPLACE_CHILD = 33;
export const OP_NODE_HAS_CHILD_NODES = 34;
export const OP_NODE_GET_PARENT_NODE = 35;
export const OP_NODE_GET_PARENT_ELEMENT = 36;
export const OP_NODE_GET_CHILD_NODES = 37;
export const OP_NODE_GET_FIRST_CHILD = 38;
export const OP_NODE_GET_LAST_CHILD = 39;
export const OP_NODE_GET_NEXT_SIBLING = 40;
export const OP_NODE_GET_PREVIOUS_SIBLING = 41;
export const OP_NODE_GET_TEXT_CONTENT = 42;
export const OP_NODE_SET_TEXT_CONTENT = 43;
export const OP_NODE_CLONE_NODE = 44;
export const OP_NODE_CONTAINS = 45;
export const OP_NODE_GET_NODE_TYPE = 46;
export const OP_NODE_GET_NODE_NAME = 47;
export const OP_NODE_GET_NODE_VALUE = 48;
export const OP_NODE_SET_NODE_VALUE = 49;
export const OP_NODE_GET_DATA = 50; // Text/Comment .data
export const OP_NODE_SET_DATA = 51;
export const OP_NODE_DISPATCH_EVENT = 52;
export const OP_NODE_IS_EQUAL_NODE = 53;

// Element
export const OP_ELEMENT_SET_ATTRIBUTE = 60;
export const OP_ELEMENT_GET_ATTRIBUTE = 61;
export const OP_ELEMENT_REMOVE_ATTRIBUTE = 62;
export const OP_ELEMENT_HAS_ATTRIBUTE = 63;
export const OP_ELEMENT_GET_TAG_NAME = 64;
export const OP_ELEMENT_GET_ID = 65;
export const OP_ELEMENT_SET_ID = 66;
export const OP_ELEMENT_GET_CLASS_NAME = 67;
export const OP_ELEMENT_SET_CLASS_NAME = 68;
export const OP_ELEMENT_CLASS_LIST_ADD = 69;
export const OP_ELEMENT_CLASS_LIST_REMOVE = 70;
export const OP_ELEMENT_CLASS_LIST_TOGGLE = 71;
export const OP_ELEMENT_CLASS_LIST_CONTAINS = 72;
export const OP_ELEMENT_GET_STYLE_PROP = 73;
export const OP_ELEMENT_SET_STYLE_PROP = 74;
export const OP_ELEMENT_GET_INNER_HTML = 75;
export const OP_ELEMENT_SET_INNER_HTML = 76;
export const OP_ELEMENT_GET_OUTER_HTML = 77;
export const OP_ELEMENT_QUERY_SELECTOR = 78;
export const OP_ELEMENT_QUERY_SELECTOR_ALL = 79;
export const OP_ELEMENT_GET_CLIENT_WIDTH = 80;
export const OP_ELEMENT_GET_CLIENT_HEIGHT = 81;
export const OP_ELEMENT_GET_BOUNDING_CLIENT_RECT = 82;
export const OP_ELEMENT_FOCUS = 83;
export const OP_ELEMENT_BLUR = 84;
export const OP_ELEMENT_CLICK = 85;
export const OP_ELEMENT_SCROLL_INTO_VIEW = 86;
export const OP_ELEMENT_SET_ATTRIBUTE_NS = 87;
export const OP_ELEMENT_GET_ATTRIBUTE_NS = 88;
export const OP_ELEMENT_REMOVE_ATTRIBUTE_NS = 89;
export const OP_ELEMENT_HAS_ATTRIBUTE_NS = 90;
export const OP_ELEMENT_GET_STYLE_CSS_TEXT = 91;
export const OP_ELEMENT_SET_STYLE_CSS_TEXT = 92;
export const OP_ELEMENT_GET_OFFSET_WIDTH = 93;
export const OP_ELEMENT_GET_OFFSET_HEIGHT = 94;
export const OP_ELEMENT_GET_SCROLL_TOP = 95;
export const OP_ELEMENT_SET_SCROLL_TOP = 96;
export const OP_ELEMENT_GET_SCROLL_LEFT = 97;
export const OP_ELEMENT_SET_SCROLL_LEFT = 98;
export const OP_ELEMENT_GET_SCROLL_HEIGHT = 99;

// Window
export const OP_WINDOW_GET_INNER_WIDTH = 100;
export const OP_WINDOW_GET_INNER_HEIGHT = 101;
export const OP_WINDOW_GET_DEVICE_PIXEL_RATIO = 102;
export const OP_WINDOW_GET_SCROLL_X = 103;
export const OP_WINDOW_GET_SCROLL_Y = 104;
export const OP_WINDOW_SCROLL_TO = 105;
export const OP_WINDOW_REQUEST_ANIMATION_FRAME = 106;
export const OP_WINDOW_CANCEL_ANIMATION_FRAME = 107;
export const OP_WINDOW_GET_COMPUTED_STYLE = 108;
export const OP_WINDOW_GET_SCROLL_WIDTH = 109;
export const OP_WINDOW_GET_SCROLL_HEIGHT = 110;
export const OP_WINDOW_ADD_EVENT_LISTENER = 111;
export const OP_WINDOW_REMOVE_EVENT_LISTENER = 112;
export const OP_WINDOW_POST_MESSAGE = 113;

// EventTarget
export const OP_ADD_EVENT_LISTENER = 120;
export const OP_REMOVE_EVENT_LISTENER = 121;

// Element children (HTMLCollection-like)
export const OP_ELEMENT_GET_CHILDREN = 130;
export const OP_ELEMENT_GET_CHILD_ELEMENT_COUNT = 131;
export const OP_ELEMENT_REMOVE = 132; // element.remove()
export const OP_ELEMENT_BEFORE = 133;
export const OP_ELEMENT_AFTER = 134;
export const OP_ELEMENT_REPLACE_WITH = 135;
export const OP_ELEMENT_CLOSEST = 136;
export const OP_ELEMENT_MATCHES = 137;
export const OP_ELEMENT_GET_TEMPLATE_CONTENT = 138; // HTMLTemplateElement.content

export const OP_ID_MAX = 255;
